### ISSUE TITLE
Freeze markupsafe to version 2.0.1 in requirements.txt

### ISSUE THREAD

**Issue by Toctave** [boreshkinai/delta-interpolator#11]
Hi again,
Running the container on Ubuntu 22.10 yields the following docker logs :

```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/opt/conda/lib/python3.7/site-packages/notebook/notebookapp.py", line 43, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/opt/conda/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/conda/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/conda/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/conda/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/conda/lib/python3.7/site-packages/markupsafe/__init__.py)
```

Freezing the `markupsafe` version by adding `markupsafe==2.0.1` in `requirements.txt` fixes the issue.

**Comment by boreshkinai** [comment]
yes, added to requirements, thanks!
