### ISSUE TITLE
Running on Ubuntu 22.10 : can't use nvidia-docker, running into hydra error without docker

### ISSUE THREAD

**Issue by Toctave** [boreshkinai/delta-interpolator#12]
Hi again,

To avoid any additional [XY problem](https://xyproblem.info/), here's what I'm trying to do : I'd like to run your code, but I only have a Ubuntu 22.10 machine at hand. `nvidia-docker` does not work with Ubuntu 22.10 ([see this](https://github.com/NVIDIA/nvidia-container-toolkit/issues/228)), hence I tried running everything inside a 22.04 VirtualBox VM. That does not work, because the VM can't get proper access to the GPU.  

To avoid all this, I tried running the code without docker, but that triggers an exception when initializing the dataset : 

```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.22.2ubuntu3 is an invalid version and will not be supported in a future release
  warnings.warn(
$HOME/.local/lib/python3.10/site-packages/hydra/experimental/initialize.py:43: UserWarning: hydra.experimental.initialize() is no longer experimental. Use hydra.initialize()
  deprecation_warning(message=message)
$HOME/.local/lib/python3.10/site-packages/hydra/experimental/initialize.py:45: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  self.delegate = real_initialize(
$HOME/.local/lib/python3.10/site-packages/hydra/experimental/compose.py:25: UserWarning: hydra.experimental.compose() is no longer experimental. Use hydra.compose()
  deprecation_warning(message=message)
$HOME/.local/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'model/lafan_inbetween_default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
Traceback (most recent call last):
  File "$HOME/.local/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
TypeError: LafanSequenceDataset.__init__() missing 1 required positional argument: 'source'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "delta-interpolator/run.py", line 143, in <module>
    main(filepath=args.config, overrides=args.overrides)
  File "delta-interpolator/run.py", line 133, in main
    run(cfg.model)
  File "delta-interpolator/run.py", line 47, in run
    dm = instantiate(cfg.dataset)
  File "$HOME/.local/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "$HOME/.local/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 334, in instantiate_node
    value = instantiate_node(
  File "$HOME/.local/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 339, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "$HOME/.local/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'src.data.batched_sequence_dataset.LafanSequenceDataset':
TypeError("LafanSequenceDataset.__init__() missing 1 required positional argument: 'source'")
full_key: dataset.backbone
```

Now I know that the Dockerfile was provided to help with reproducibility and I'm bypassing all of that, but I feel out of options here and I don't want to downgrade my OS to run this. I haven't been able to fix the above errors by digging into the code a bit, but maybe this'll be clearer to you ?

Would appreciate any help!

**Comment by MengHao666** [comment]
Have you solved the problem?

**Comment by MengHao666** [comment]
this problem is caused by the version of hydra. you could reinstall the version of which is in readme.md.
